In [1]:
from MCAmo import MCA
import numpy as np
from calculate_MC_copy import compute_MC_and_grad_MC
import time

o_dict = {
        "1": {"2": 1, "3": 1,"9" : 1,"11" : 1, "6": 3,"7" : 3,"12" : 6},
        "8": {"2": 1, "3": 1,"9" : 1,"11" : 1, "6": 3,"7" : 3,"12" : 6},
        "13": {"2": 1, "3": 1,"9" : 1,"11" : 1, "6": 3,"7" : 3,"12" : 6},
        "14": {"2": 1, "3": 1,"9" : 1,"11" : 1, "6": 3,"7" : 3,"12" : 6},
        "15": {"2": 1, "3": 1,"9" : 1,"11" : 1, "6": 3,"7" : 3,"12" : 6}

    }
r_dict = {
        "2": {"4": 1, "5":1,"10":1},
        "3": {"4": 1, "5":1,"10":1},
        "9": {"4": 1, "5":1,"10":1},
        "11" : {"4": 1, "5":1,"10":1}
    }
s_dict = {
        "4": {"2": 1, "3": 1,"9" : 1,"11" : 1, "6": 6,"7" : 6,"12" : 6},
        "5": {"2": 1, "3": 1,"9" : 1,"11" : 1, "6": 6,"7" : 6,"12" : 6},
        "10": {"2": 1, "3": 1,"9" : 1,"11" : 1, "6": 6,"7" : 6,"12" : 6} 
    }
d_dict = {
        "6": {},
        "7" : {},
        "12": {}
    }

# o_dict = {"1": {"3":1, "4":1, "7":5, "8":6},
#           "2": {"3":1, "4":1, "7":5, "8":6}
# }

# r_dict = {"3": {"5":1, "6":2},
#           "4": {"5":2, "6":1}
# }

# s_dict = {"5": {"3":1, "4":2, "7":6, "8":7},
#           "6": {"3":2, "4":1, "7":7, "8":6}
# }

# d_dict = {"7": {},
#           "8": {}
# }

n_size = 5

r_size = len(r_dict)
s_size = len(s_dict)
o_size = len(o_dict)
d_size = len(d_dict)

theta_p = 2
theta_c = 2
K = 2

v = np.zeros((r_size,s_size))
v +=1

c_rs = np.zeros((r_size, s_size, K))
# shipper_do_cost_choices = [4,5,6]
# shipper_dont_cost_choices = [10,11,12]
for rr in range(r_size):
    for ss in range(s_size):
        c_rs[rr, ss, 1] = 2 #doesn't have an impact on distribution, and final price.
        c_rs[rr, ss, 0] = c_rs[rr, ss, 1] + 1 # cost difference # has an impact higher difference, more incentives to do deliveries.

z_rs_bar = np.zeros((r_size,s_size))
z_rs_bar += 10
y_od_bar = np.zeros((o_size,d_size))
y_od_bar += 2

print("MCA from MCAmo:")
start_time = time.time()
MCA(o_dict, d_dict, r_dict, s_dict, n_size, z_rs_bar, y_od_bar, theta_p, theta_c, K, c_rs, v)
end_time = time.time()
print("time:", end_time - start_time, "seconds")

print()
print("="*100)
print()

seed = 42
print("calculate_MC:")
start_time = time.time()
MC, grad_MC = compute_MC_and_grad_MC(o_dict, r_dict, s_dict, d_dict, n_size, K, theta_p, theta_c, z_rs_bar, y_od_bar, c_rs, seed, v)
end_time = time.time()
print("MC:", MC)
print("grad_MC:", grad_MC)
print("time:", end_time - start_time, "seconds")

MCA from MCAmo:
MC: 424.3793447472789
grad_MC: [[2.31365448 2.35890911 2.77010263]
 [2.41558533 2.55550893 2.58113037]
 [2.45980297 2.32607002 2.1577132 ]
 [2.35162469 2.29057837 2.36251085]]
time: 0.015624046325683594 seconds


calculate_MC:
MC: 424.3793447472789
grad_MC: [[2.31365448 2.35890911 2.77010263]
 [2.41558533 2.55550893 2.58113037]
 [2.45980297 2.32607002 2.1577132 ]
 [2.35162469 2.29057837 2.36251085]]
time: 0.0 seconds
