In [1]:
from MCAmo import MCA
import numpy as np

# o_dict = {
#         "1": {"2": 1, "3": 1,"9" : 1,"11" : 1, "6": 3,"7" : 3,"12" : 6},
#         "8": {"2": 1, "3": 1,"9" : 1,"11" : 1, "6": 3,"7" : 3,"12" : 6},
#         "13": {"2": 1, "3": 1,"9" : 1,"11" : 1, "6": 3,"7" : 3,"12" : 6},
#         "14": {"2": 1, "3": 1,"9" : 1,"11" : 1, "6": 3,"7" : 3,"12" : 6},
#         "15": {"2": 1, "3": 1,"9" : 1,"11" : 1, "6": 3,"7" : 3,"12" : 6}

#     }
# r_dict = {
#         "2": {"4": 1, "5":1,"10":1},
#         "3": {"4": 1, "5":1,"10":1},
#         "9": {"4": 1, "5":1,"10":1},
#         "11" : {"4": 1, "5":1,"10":1}
#     }
# s_dict = {
#         "4": {"2": 1, "3": 1,"9" : 1,"11" : 1, "6": 6,"7" : 6,"12" : 6},
#         "5": {"2": 1, "3": 1,"9" : 1,"11" : 1, "6": 6,"7" : 6,"12" : 6},
#         "10": {"2": 1, "3": 1,"9" : 1,"11" : 1, "6": 6,"7" : 6,"12" : 6} 
#     }
# d_dict = {
#         "6": {},
#         "7" : {},
#         "12": {}
    # }

o_dict = {"1": {"3":1, "4":1, "7":5, "8":6},
          "2": {"3":1, "4":1, "7":5, "8":6}
}

r_dict = {"3": {"5":1, "6":2},
          "4": {"5":2, "6":1}
}

s_dict = {"5": {"3":1, "4":2, "7":6, "8":7},
          "6": {"3":2, "4":1, "7":7, "8":6}
}

d_dict = {"7": {},
          "8": {}
}

n_size = 5

r_size = len(r_dict)
s_size = len(s_dict)

theta_p = 2
v = np.zeros((r_size,s_size))
v +=1

MCA(o_dict, d_dict, r_dict, s_dict, n_size, theta_p, v)

1 [[[[0.11523336 0.11523336]
   [0.01559514 0.01559514]]

  [[0.01559514 0.01559514]
   [0.00211057 0.00211057]]]


 [[[0.00211057 0.00211057]
   [0.01559514 0.01559514]]

  [[0.01559514 0.01559514]
   [0.11523336 0.11523336]]]]
2 [[[[0.13191716 0.13191716]
   [0.01785305 0.01785305]]

  [[0.01785305 0.01785305]
   [0.00241615 0.00241615]]]


 [[[0.00241615 0.00241615]
   [0.01785305 0.01785305]]

  [[0.01785305 0.01785305]
   [0.13191716 0.13191716]]]]
3 [[[[0.13474162 0.13474162]
   [0.0182353  0.0182353 ]]

  [[0.0182353  0.0182353 ]
   [0.00246788 0.00246788]]]


 [[[0.00246788 0.00246788]
   [0.0182353  0.0182353 ]]

  [[0.0182353  0.0182353 ]
   [0.13474162 0.13474162]]]]
4 [[[[0.1352318  0.1352318 ]
   [0.01830163 0.01830163]]

  [[0.01830163 0.01830163]
   [0.00247686 0.00247686]]]


 [[[0.00247686 0.00247686]
   [0.01830163 0.01830163]]

  [[0.01830163 0.01830163]
   [0.1352318  0.1352318 ]]]]
